- kef/hw-turn-in-behavior.md
- kef/hw-turn-in-behavior.md~
Divided turn-in behavior into alpha and mvp. We can discuss at the change request meeting, tomorrow.
> Turn in alpha

- phil/s010-css-topics.md
@philschatz adding some links to stuff about naming and css organization
> Add links to BEM ideas

- jp/exercise_sources.md
@philschatz - ok with this change?
> removed id and type from related_content, can add back later if useful

- kevin/personalized_exercise_behavior_hw.md
> Update with Drew's rewrite to add emphasis on the correct approach.

- jp/reference_book_apis.md
> fix blatant errors

- phil/what-is-master.md
/cc @jpslav: It's probably easier to just view the rendered MD file than sift through the diff
> Update "What is Master?"

- phil/workflow-idea.md
Feedback/suggestion discussion appreciated :smile: 
/cc @dak
> Workflow Updates

- reedstrm/problem-domain--coordinated-legacy-publish.md
Proposing some other solutions for discussion...
Traces back to [an analysis card in the CTE sprint](https://trello.com/c/tkeEFoEN/34-how-will-cnx-publishing-know-to-cook-content-published-by-zope).
(CC @reedstrm @karenc )
> CNX discussion on "Problem Domain: Legacy Publish in the World of Cook HTML at Publish"

- phil/deploy.sh
This addresses a corner-case of needing to update the deployment scripts in order to successfully deploy (ie upgrading ruby versions)
> support deploying tutor-deployment updates as well as other repos

- pumazi/cnx/planning--dms-editing-tools.org
@pumazi 
Fixed some typos while reading; I think the 4 phases make sense. How much of the code could be reused in each phase between the DMS-solution and the final implementation? For example
- could some/most of the `completezip -> ePUB` code be reused to migrate existing content?
- could cnxauthoring be completely bypassed for DMS's?
Also, I wonder if the service could be designed to work with GitHub Webhooks to provide validation (and preview PDF generation) on push 😄 . It would require:
- pull content from a Git URL instead of pushing a zip
- sending a service POST to a GitHub URL (saying success/failure)
/cc @rich-hart
> :art: fix typos

- CONTRIBUTING.md
Testing out meta PR to the instructions for my other PR.
I like that we are creating these guidelines!
> Made two sentences out of run-on.

- pumazi/cnx/planning--dms-editing-tools.org
Makes it easier to know what the link goes to.
> Add doc title to link.

- phil/workflow-idea.md
> more workflow updates

- helene/reqs.md
I'm reading through your notes and will try to rephrase them in an "As a `[type-of-user]` I want to `[desired goal]` so `[reasons]`" format which might help me in understanding each of the bullets (✅ ). These were my _rough_ notes from our discussion on Friday. We can discuss the format and I can elaborate more for ones that are not clear.
Stories are in the form _As a `[type-of-user]` I want to `[desired goal]` so `[reasons]`_
> Some suggestions for easybake-recipe stories

- checklists.md
> clarify LDAP and add Google Drive access

- cop/versioning-proposal.md
For discussing a [proposal for versioning](https://github.com/openstax/napkin-notes/blob/version-cop/cop/versioning-proposal.md)
> Proposal for versioning

- phil/2016-easybake-holiday.md
Adding some clarifications of ideas
> clarifications of ⛄️ ❄️ 🏂  Holiday ideas

- phil/2016-easybake-holiday.md
to see where the content came from (like a Symbol Table 😄 )
> add sourcemaps to HTML files

- phil/js-css-preprocessor.md
... instead of LESS/SASS.
Added here to facilitate discussion (add comments to the diff in the PR).
> Proposal: Use JavaScript as the CSS Preprocessor

- tech-talks.md
This updates the schedule & slides for tech talks.
/cc @pandafulmanda @mwharrison @Dantemss
> Update Schedule for tech-talks
